theme: jekyll-theme-minimal
title: Maxime Hanicotte
description: GitHub Page on my profil and my projects
logo: https://avatars2.githubusercontent.com/u/12615544?s=400&u=1dfdaf9df2d3729ae02b24c71bde9f83d923be9b&v=4
show_downloads: false
google_analytics: UA-143672565-1
