theme: jekyll-theme-minimal
title: Maxime Hanicotte
description: A short description of my profile and my projects
logo: https://avatars2.githubusercontent.com/u/12615544?s=460&v=4
show_downloads: true
google_analytics: [Your Google Analytics tracking ID]
